<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mustache</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)
		(&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)\b.*?&gt;
		|&lt;!--(?!.*--&gt;)
		|\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
		)</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		(&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)&gt;
		|^\s*--&gt;
		|(^|\s)\}
		)</string>
	<key>name</key>
	<string>HTML with mustaches</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\{\{!</string>
			<key>end</key>
			<string>\}\}</string>
			<key>name</key>
			<string>comment.block.mustache</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{\{[{&lt;&gt;#^/]?</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.mustache</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}?\}\}</string>
			<key>name</key>
			<string>source.mustache.embedded.html</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.mustache</string>
	<key>uuid</key>
	<string>23C9A029-DEF3-42C2-9680-ED39392876E1</string>
</dict>
</plist>
